version: '3'
services:
  db:
    image: mysql:5.6
    volumes:
      - db-volume:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolioec_development
    ports:
      - "4306:3306"
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - .:/portfolioec
    ports:
      - 3000:3000
    links:
      - db
volumes:
  db-volume: