version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.0-node-browsers
      environment:
        - BUNDLER_VERSION: 2.0.2
        - RAILS_ENV: test
    - image: circleci/mysql:5.7
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '%'
        - MYSQL_DB: portfolioec_test
        - MYSQL_USER: user
    working_directory: ~/portfolioec

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Use specific database.yml
          command: mv ./config/database.yml.ci ./config/database.yml

      - run:
          name: Databasesetup
          command: |
            bin/rails db:create
            bin/rails db:migrate
      - run:
          name: yarn Install
          command: yarn install

      - run: bundle exec bin/webpack

      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  rubocop:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
        - BUNDLER_VERSION: 2.0.2
        - RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '%'
        - MYSQL_DB: portfolioec_test
        - MYSQL_USER: user
    working_directory: ~/portfolioec
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - 95:b5:ac:4a:00:b5:68:f8:e3:ab:43:3c:b0:53:b4:62
      - run: ssh -p $SSH_PORT $USER_NAME@$HOST_NAME "cd /home/ec2-user/my_app/ && git pull origin master"

workflows:
    version: 2
    deploy:
      jobs:
        - build
        - rubocop:
            requires:
              - build
        - deploy:
            requires:
              - rubocop
              - build
            filters:
              branches:
                only: master
